# Generated by Django 3.2 on 2023-02-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Mysql"), ("2", "Postgresql"), ("3", "Redis")],
                        max_length=20,
                    ),
                ),
                ("connect_param", models.TextField()),
                ("user_id", models.IntegerField()),
            ],
            options={
                "db_table": "connect",
                "default_permissions": ("add", "change", "delete", "view"),
            },
        ),
    ]
