# Generated by Django 3.2 on 2023-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connection", "0002_alter_connection_connect_param"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="type",
            field=models.CharField(
                choices=[("1", "Mysql"), ("2", "Redis")], max_length=20
            ),
        ),
    ]
