# Generated by Django 3.2.18 on 2023-03-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("10", "参数"),
                            ("20", "结果"),
                            ("30", "http请求"),
                            ("40", "SQL执行"),
                            ("50", "redis操作"),
                            ("60", "工具引用"),
                            ("70", "自定义工具"),
                        ],
                        max_length=32,
                        verbose_name="步骤类型",
                    ),
                ),
                (
                    "content",
                    models.JSONField(blank=True, null=True, verbose_name="步骤内容"),
                ),
                ("task_id", models.IntegerField(db_index=True, verbose_name="taskId")),
            ],
            options={
                "db_table": "step",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=128, unique=True, verbose_name="名称"
                    ),
                ),
                (
                    "mark",
                    models.CharField(
                        db_index=True, max_length=128, unique=True, verbose_name="标识"
                    ),
                ),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "steps",
                    models.JSONField(blank=True, null=True, verbose_name="任务包含的步骤信息"),
                ),
                ("nums", models.IntegerField(default=0, verbose_name="执行次数")),
                ("status", models.BooleanField(default=False, verbose_name="上下线状态")),
                ("user_id", models.IntegerField(verbose_name="创建人ID")),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskRunStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("plan_id", models.CharField(max_length=128, verbose_name="本次执行唯一id")),
                ("task_id", models.IntegerField(verbose_name="taskId")),
                ("status", models.BooleanField(default=False, verbose_name="是否执行完成")),
            ],
            options={
                "db_table": "task_status",
                "index_together": {("plan_id", "task_id")},
            },
        ),
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("plan_id", models.CharField(max_length=128, verbose_name="本次执行唯一id")),
                ("content", models.TextField(blank=True, verbose_name="执行结果")),
                ("task_id", models.IntegerField(verbose_name="taskId")),
                ("step_id", models.IntegerField(verbose_name="stepId")),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("10", "参数"),
                            ("20", "结果"),
                            ("30", "http请求"),
                            ("40", "SQL执行"),
                            ("50", "redis操作"),
                            ("60", "工具引用"),
                            ("70", "自定义工具"),
                        ],
                        max_length=32,
                        verbose_name="步骤类型",
                    ),
                ),
            ],
            options={
                "db_table": "task_result",
                "index_together": {("plan_id", "task_id")},
            },
        ),
    ]
